import { AwardTheme, AwardType, ScrollFont } from './types';

export const DEFAULT_SCROLL_DATA = {
  location: 'Amtgard',
  recipient: 'Lady Alara',
  awardType: AwardType.WARRIOR,
  customAwardName: '',
  awardLevel: 1,
  date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
  giver: 'King Arion',
  reason: 'For valor shown upon the field of battle against the goblin hordes, demonstrating skill with sword and shield unsurpassed by her peers.',
  theme: {
    id: 'warrior',
    name: 'Warrior Red',
    bgGradient: 'from-amber-50 to-amber-100',
    borderColor: 'border-red-900',
    accentColor: 'text-red-900',
    textureOpacity: 0.1,
  },
  titleFont: ScrollFont.ANCIENT,
  bodyFont: ScrollFont.CINZEL,
  recipientFont: ScrollFont.ANCIENT,
  signatureFont: ScrollFont.ANCIENT,
  heraldryImage: null,
  heraldryPosition: 'bottom-center' as const,
  
  // Defaults
  orientation: 'portrait' as const,
  titleFontSize: 64,
  recipientFontSize: 56,
  bodyFontSize: 24,
  signatureFontSize: 24,
};

export const THEMES: AwardTheme[] = [
  {
    id: 'warrior',
    name: 'Warrior Red',
    bgGradient: 'from-orange-50 to-orange-100',
    borderColor: 'border-red-800',
    accentColor: 'text-red-900',
    textureOpacity: 0.2,
  },
  {
    id: 'dragon',
    name: 'Dragon Green',
    bgGradient: 'from-emerald-50 to-green-100',
    borderColor: 'border-emerald-800',
    accentColor: 'text-emerald-900',
    textureOpacity: 0.15,
  },
  {
    id: 'rose',
    name: 'Rose White',
    bgGradient: 'from-rose-50 to-pink-50',
    borderColor: 'border-rose-400',
    accentColor: 'text-rose-800',
    textureOpacity: 0.1,
  },
  {
    id: 'smith',
    name: 'Smith Iron',
    bgGradient: 'from-stone-100 to-stone-200',
    borderColor: 'border-stone-700',
    accentColor: 'text-stone-800',
    textureOpacity: 0.3,
  },
  {
    id: 'lion',
    name: 'Lion Gold',
    bgGradient: 'from-yellow-50 to-amber-100',
    borderColor: 'border-yellow-600',
    accentColor: 'text-amber-800',
    textureOpacity: 0.15,
  },
  {
    id: 'owl',
    name: 'Owl Blue',
    bgGradient: 'from-slate-50 to-blue-50',
    borderColor: 'border-blue-800',
    accentColor: 'text-blue-900',
    textureOpacity: 0.1,
  },
   {
    id: 'necromantic',
    name: 'Dark Arts',
    bgGradient: 'from-stone-300 to-stone-400',
    borderColor: 'border-black',
    accentColor: 'text-purple-900',
    textureOpacity: 0.4,
  },
];

export const FONTS = [
  { label: 'Medieval Sharp', value: ScrollFont.MEDIEVAL },
  { label: 'Cinzel (Roman)', value: ScrollFont.CINZEL },
  { label: 'Grenze Gotisch (Blackletter)', value: ScrollFont.GOTHIC },
  { label: 'Pirata One (Gothic)', value: ScrollFont.PIRATE },
  { label: 'Uncial Antiqua (Celtic)', value: ScrollFont.ANCIENT },
  { label: 'IM Fell English SC (Print)', value: ScrollFont.PRINT },
  { label: 'Marcellus SC (Classic)', value: ScrollFont.ROMAN },
  { label: 'Great Vibes (Script)', value: ScrollFont.SCRIPT },
  { label: 'Pinyon Script (Royal)', value: ScrollFont.ROYAL },
  { label: 'Italianno (Elegant)', value: ScrollFont.ITALIAN },
  { label: 'Tangerine (Tall)', value: ScrollFont.TALL },
];